flags: {}
extra-package-dbs: []
packages:
- '.'
- '../histogram-extras.git/'
extra-deps:
- diagrams-pgf-0.1.0.4
- texrunner-0.0.1.1
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-6.10
